# Minimal embedded configuration - External config takes precedence
# External configuration files should be placed in config/ directory

server:
  port: 8080

spring:
  application:
    name: gateway
  profiles:
    active: development

# Basic health check configuration
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when-authorized

# Default logging until external config is loaded
logging:
  level:
    root: INFO
    com.numaansystems.gateway: INFO
